CREATE DATABASE IF NOT EXISTS delta_app;
USE delta_app;

CREATE TABLE IF NOT EXISTS user (
  id VARCHAR(50) PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(80) UNIQUE NOT NULL,
  password VARCHAR(50) NOT NULL
);
